services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  django-web:
    build: .
    container_name: django-docker
    # command: gunicorn spedger.wsgi:application --bind 0.0.0.0:8000 --timeout 180
    command: gunicorn spedger.wsgi:application --bind 0.0.0.0:8000 --access-logfile - --error-logfile - --log-level debug --timeout 30     # to see the entries like in runserver
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    env_file:
      - .env
    restart: always

  celery-worker:
    build: .
    command: celery -A spedger worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: always

  redis:
    image: redis:7
    restart: always

  celery-beat:
    build: .
    command: celery -A spedger beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/app/staticfiles:ro
    depends_on:
      - django-web
    restart: always

volumes:
  postgres_data:
