# Generated by Django 6.0 on 2025-12-23 22:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('settled', models.BooleanField(default=False)),
                ('settled_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('private_group', models.BooleanField(default=False)),
                ('group_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('profile_src', models.URLField(blank=True, null=True)),
                ('fav_team', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality', models.CharField(max_length=200)),
                ('reason', models.CharField(choices=[('fun', 'Fun'), ('addiction', 'Addiction'), ('record', 'Record')], max_length=20)),
                ('private_acct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reveal_slips', models.BooleanField(default=True)),
                ('log_all_slips', models.BooleanField(default=False)),
                ('friends', models.ManyToManyField(blank=True, related_name='user_friends', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='group_members', to='spedger_main.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_code', models.CharField(max_length=30)),
                ('settled', models.BooleanField(default=False)),
                ('slip_won', models.BooleanField(default=False)),
                ('total_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('weekly', models.BooleanField(default=False)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DuellistInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.BooleanField(default=False)),
                ('duel_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duellists', to='spedger_main.duel')),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel', to='spedger_main.slip')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slip', to='spedger_main.slip')),
            ],
        ),
        migrations.CreateModel(
            name='SlipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.JSONField()),
                ('pick', models.CharField(max_length=200)),
                ('market', models.CharField(max_length=200)),
                ('sport', models.CharField(max_length=50)),
                ('competition', models.CharField(blank=True, max_length=200, null=True)),
                ('event_odd', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('event_won', models.BooleanField(default=False)),
                ('event_settled', models.BooleanField(default=False)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slip_events', to='spedger_main.slip')),
            ],
        ),
    ]
