# Generated by Django 6.0 on 2025-12-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0001_created_initial_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'verbose_name_plural': 'DiaryEntries'},
        ),
        migrations.AlterModelOptions(
            name='duellistinfo',
            options={'verbose_name_plural': 'DuellistInfo'},
        ),
    ]
