# Generated by Django 6.0 on 2026-01-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0004_remove_friendrequest_accepted_friendrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slipevent',
            name='event_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='slipevent',
            name='participants',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
