# Generated by Django 6.0 on 2026-01-02 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0005_corrected_slip_and_slipevent_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 2, 14, 37, 5, 738702, tzinfo=datetime.timezone.utc)),
        ),
    ]
