# Generated by Django 6.0 on 2026-01-02 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0007_alter_diaryentry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='duel',
            name='minimum_odds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
