# Generated by Django 6.0 on 2026-01-02 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0008_duel_created_at_duel_minimum_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duellistinfo',
            name='slip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duel', to='spedger_main.slip'),
        ),
    ]
