# Generated by Django 6.0 on 2026-01-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0009_alter_duellistinfo_slip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duel',
            name='accepted',
        ),
        migrations.AddField(
            model_name='duel',
            name='duel_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='open', max_length=15, null=True),
        ),
    ]
