# Generated by Django 6.0 on 2026-01-09 10:29

import spedger_main.model_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0013_diaryentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_src',
        ),
        migrations.AddField(
            model_name='profile',
            name='background_img',
            field=models.CharField(default=spedger_main.model_helpers.background_img_func, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.CharField(default=spedger_main.model_helpers.avatar_img_func, max_length=50),
        ),
    ]
