# Generated by Django 6.0 on 2026-01-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0014_fixing_avatar_and_adding_background_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_img',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
