# Generated by Django 6.0 on 2026-01-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0016_groupchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='leader_talk_only',
            field=models.BooleanField(default=False),
        ),
    ]
