# Generated by Django 6.0 on 2026-01-12 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0017_group_leader_talk_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
