# Generated by Django 6.0 on 2026-01-12 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0018_group_created_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='banned_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups_banned_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
