# Generated by Django 6.0 on 2026-01-12 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0019_adding_banned_users_to_group_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='banned_users',
            field=models.ManyToManyField(blank=True, related_name='groups_banned_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
