# Generated by Django 6.0 on 2026-01-13 07:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0021_groupchatmsgs_delete_groupchat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='GroupChat',
        ),
    ]
