# Generated by Django 6.0 on 2026-01-15 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0022_renamed_Group_model_to_GroupChat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='users_viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
