# Generated by Django 6.0 on 2026-01-16 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0023_added_viewers_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='muted_users',
            field=models.ManyToManyField(blank=True, related_name='users_muted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
