# Generated by Django 6.0 on 2026-01-16 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0024_adding_muted_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('current_game', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyGameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wkly_game_slip', to='spedger_main.slip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wkly_game_performances', to=settings.AUTH_USER_MODEL)),
                ('wkly_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_participants', to='spedger_main.weeklygame')),
            ],
        ),
    ]
