# Generated by Django 5.2.11 on 2026-02-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0025_created_weekly_game_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='slipevent',
            name='event_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
