# Generated by Django 5.2.11 on 2026-02-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0026_slipevent_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatmsgs',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
