# Generated by Django 5.2.11 on 2026-02-27 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0027_groupchatmsgs_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchatmsgs',
            name='expired',
        ),
    ]
