# Generated by Django 5.2.11 on 2026-02-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0028_remove_groupchatmsgs_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='slipevent',
            name='event_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slipevent',
            name='event_postponed',
            field=models.BooleanField(default=False),
        ),
    ]
