# Generated by Django 5.2.11 on 2026-03-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0029_slipevent_event_cancelled_slipevent_event_postponed'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklygameparticipant',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
