# Generated by Django 5.2.11 on 2026-03-19 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0030_weeklygameparticipant_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklygameparticipant',
            old_name='rank',
            new_name='ranking',
        ),
    ]
