# Generated by Django 5.2.11 on 2026-03-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0031_rename_rank_weeklygameparticipant_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_class', models.CharField(max_length=100)),
                ('error_txt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
