# Generated by Django 6.0.8 on 2026-09-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0032_customerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='slipevent',
            name='market_group',
            field=models.CharField(choices=[('team', 'Team'), ('player', 'Player')], default='team', max_length=10),
        ),
    ]
