# Generated by Django 6.0.8 on 2026-09-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spedger_main', '0033_slipevent_market_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='slipevent',
            name='player_involved',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
